### ISSUE TITLE
Top navigation doesn't indicate in which section you're in

### ISSUE THREAD

**Issue by wesjon** [fabiomsr/from-java-to-kotlin#10]
Take a look at the image below. As you can see there is no way of telling in which section you're in. Users might miss checking other sections if they don't realize these are navigation links. 

![image](https://user-images.githubusercontent.com/2665419/27084099-0adb0952-5021-11e7-9c32-75de4e60bc67.png)

My suggestion is to add a selected state, a line below the current section or a different background, to the current section.

**Comment by fabiomsr** [comment]
Done, thanks. :+1:
